### ISSUE TITLE
Proxy instructions for Apache

### ISSUE THREAD

**Issue by pguth** [pump-io/pump.io#1032]
Please enhance the proxy support of Pump.io!

Currently I am blocked from using it because I just cannot get it to function properly behind an Apache proxy. Duckduckgo'ing around figure that this is a problem many people have and since we all would like to see Pump.io prevail I feel this is an essential issue.

---

I chipped in with a [10$ bounty](https://www.bountysource.com/issues/2746239-proxy-support).

**Comment by strugee** [comment]
Closing as it's currently possible to proxy pump.io behind Apache. Realtime won't work, but we can't do anything about that because it's just something Apache can't cope with.

If anyone has a proxying use-case not covered by existing functionality, file a new issue.
