### ISSUE TITLE
how to test password using php

### ISSUE THREAD

**Issue by mkenran** [pump-io/pump.io#1039]
Hi,
I use pump in parallel with my intranet.
I successfully connected to pump using php/oauth, i am able to get lists (favorites, followers) from users already registered.
I would like to register automatically a user from my intranet in php using the api.
What are the PATH, params ?
Regards

**Comment by ShijuDekhDekh1** [comment]
Hello,

I am developing pump.io on my iOS app. We have created server in backend. I am able to get lists (favorites, followers) from users already registered using browser not from in iOS app. But while registration, i got some error. Is their any authentication we needed? 

Actually the URL which i used is: https://hostname/api/users/
and used JSON Object to add parameters	 @"nickname" : @"sam123",
                              	  @"password" : @“sam123",
									 @“email" : @“sam123@sam123.com”

I would like to register automatically a user from my intranet in iOS app using the api.
What are the PATH, params ?

In pump.io wiki -> API.md they provided us: 
User registration

There is a collection of all users at the endpoint /api/users. To create a new user, POST a user representation (see below) to the list. You can also get the latest registered users by GETting the collection.

The JSON object representing the user has the following properties:

nickname: The user's nickname. 1-64 characters, including only ASCII capital and lowercase letters and numbers as well as "-", ".", and "_". The nickname is immutable and unique per server; it can't be changed.
password: The plain-text password. This isn't returned when you GET the user object, but you have to provide it when registering or updating the user.
profile: a "person" object. This is created automatically when you create a new user; don't try to add it yourself. Don't update this directly; update the person through its object endpoint.

Waiting your response.

**Comment by strugee** [comment]
@mkenran do you still need help here? Otherwise I'd like to close this issue
