### ISSUE TITLE
FOAF

### ISSUE THREAD

**Issue by csarven** [pump-io/pump.io#1043]
Because it makes a "dent": http://data.dws.informatik.uni-mannheim.de/lodcloud/2014/ISWC-RDB/LODCloudDiagram.png

http://data.dws.informatik.uni-mannheim.de/lodcloud/2014/ISWC-RDB/

**Comment by strugee** [comment]
@csarven can you clarify what you're looking for here? Otherwise I'll close this in a couple days as we have a _lot_ of open issues and I'd like to clean out the issue tracker

**Comment by csarven** [comment]
StatusNet's FOAF/SIOC had notable reach in the the Linked Open Data and academic community. The point was that the data was used or analysed somehow by different groups. So, continuing on that in pump.io may have been something to consider.

This is probably not so relevant now (today) since ActivityPub/ActivityStreams 2.0 will be used (as I understand it).

Ping @cwebber . Close as you see fit.

**Comment by strugee** [comment]
Neat, thanks for the response! I'm closing given the above, since we're unlikely to add new protocols to pump.io (besides AS2/AP which are basically upgrades to the existing stuff), but I'm happy to reopen if anyone has objections
