### ISSUE TITLE
Web UI has problems with complex percent-encoded URLs

### ISSUE THREAD

**Issue by msjoberg** [pump-io/pump.io#1045]
If I post a note with an URL that contains % encoded stuff it seems to break, at least for more complicated URLs like this one `http://mail-archives.apache.org/mod_mbox/incubator-general/201403.mbox/%3CCF5EEBDE.32607%25rvesse@dotnetrdf.org%3E`

The same problem occurs when I post it from a client (Pumpa). This is the html content of the post:

```
<p><a href="http://mail-archives.apache.org/mod_mbox/incubator-general/201403.mbox/%3CCF5EEBDE.32607%25rvesse@dotnetrdf.org%3E">foo</a></p>
```

The URL in the post displays correctly in Pumpa, but in the web UI it becomes translated to this invalid URL: http://mail-archives.apache.org/mod_mbox/incubator-general/201403.mbox/%3CCF5EEBDE.32607%rvesse@dotnetrdf.org%3E

**Comment by jankusanagi** [comment]
Yep, I referenced this issue in mine, because I think it's the same root cause: node.js or something is removing % when followed by some numbers (and the numbers) if n>=10.

Node.js is probably parsing the string looking to replace %ID with some parameter, like C's printf() or Qt's QString::arg() does.

**Comment by strugee** [comment]
Looks like this is now working under Node 4, pump.io 2.0.0: https://pump.strugee.net/alex/note/nob0-aOlR9Kj8u30RIPhKA. As with #1100 I suspect this was because of the old XSS scrubber.

Closing given the above. Reopen if you can still reproduce using modern versions of pump.io and Node.
