### ISSUE TITLE
set-immediate is deprecated in favour of setimmediate

### ISSUE THREAD

**Issue by diocles** [pump-io/pump.io#1049]
Hi there,

https://github.com/jussi-kalliokoski/setImmediate.js
is deprecated in favour of:
https://github.com/YuzuJS/setImmediate

I believe all that is needed is to replace "set-immediate" with "setimmediate" in the code.

Kind regards,

Tim

**Comment by strugee** [comment]
pump.io never used setimmediate, but Databank did. This has since been fixed.
