### ISSUE TITLE
<marquee> tag can mess up the web UI completely

### ISSUE THREAD

**Issue by jankusanagi** [pump-io/pump.io#1053]
So I found this user: https://identi.ca/int0x27h whose last post, ATM is https://identi.ca/int0x27h/note/wxGLg0NnRde3QNz58EvYMg

This post includes a <marquee> opening tag, but not a closing tag. This brings horrible results to the web interface, as you can see (unless your browser decided to ignore this old and often annoying tag).

I guess this could either be fixed by:
A) removing the <marquee> tag from the message at display time on the webUI (the easiest, probably)
B) pseudo-sanitizing the HTML in the posted messages at posting time, fixing this kind of thing.

I seem to recall a similar issue being brought up about the webUI getting messed up if a <i> was opened but not closed...

**Comment by strugee** [comment]
@jankusanagi can you test if this still happens under modern versions?

**Comment by jankusanagi** [comment]
I just checked. From what I see, an opened but not closed marquee tag will be properly sanitized and closed in a 2.0.5 server (datamost.com).

I used the same Dianara hack to test this in a server that still runs 0.3.0, and it clearly breaks the whole page there.

So yes, this seems fixed =)

**Comment by strugee** [comment]
Excellent!
