### ISSUE TITLE
error while executing the "pump" file 

### ISSUE THREAD

**Issue by zineboualialami** [pump-io/pump.io#1056]
When i try to execute the pump file in "bin", i have this error : 
[SyntaxError: Unexpected string]
Does anyone know how to solve this issue ? 
thankx !

**Comment by AuroraSkywalker** [comment]
I had unexpected string it was comments in my configuration file.  #

**Comment by strugee** [comment]
Closing as this issue is very old and OP has presumably fixed the problem or given up.

If you have problems again, file a new issue or get in touch with the community (see the "Community" wiki page)
