### ISSUE TITLE
youtube play button bug in pump.io web

### ISSUE THREAD

**Issue by m4rch** [pump-io/pump.io#1067]
if the homepage stream includes a post containing a video (youtube), a big play button shows on the top left of the page.

see thread:
https://identi.ca/testbeta/image/UDkaMHEbRjmrt4WQpARhZw

![screenshot](https://identi.ca/uploads/testbeta/2015/2/11/YsBuQA.png)

another example:
notice https://fmrl.me/axel/note/eAtKhqzZTGidxWYhZ1tb1g causes a link to a taylor swift mashup.

**Comment by jankusanagi** [comment]
For the sake of completeness, I'll add that that happens with a post created via Friendica, which apparently inserts broken HTML/CSS.
This is not something that happens just by including a link to youtube.com.

It would help if the linked note was public, so anyone could analize it.

**Comment by strugee** [comment]
Closing as this is probably solved by the new XSS scrubber and without a public note, we can't confirm.

If anyone has a **public** note they can reproduce this with, feel free to share and I'll happily reopen.
