### ISSUE TITLE
Registration and Login in pump.io through iOS development

### ISSUE THREAD

**Issue by ghost** [pump-io/pump.io#1068]
Hello All,

I am integrating pump.io in iOS development. I have created the server. But I am stuck with user registration/login process through the iOS app. I found the feeds, followers and following through this url:: https://hostname/api/user/nick name/feed

Trying to register in iOS mobile app: https://hostname/api/users/nickname=sam&password=sam

But bad luck. I don't know what i am missing? and please suggest me the registration process. So i can familiar with pump.io.

I found in the document of pump.io:

User registration

There is a collection of all users at the endpoint /api/users. To create a new user, POST a user representation (see below) to the list. You can also get the latest registered users by GETting the collection.

The JSON object representing the user has the following properties:

nickname: The user's nickname. 1-64 characters, including only ASCII capital and lowercase letters and numbers as well as ”-”, ”.”, and “_”. The nickname is immutable and unique per server; it can't be changed.
password: The plain-text password. This isn't returned when you GET the user object, but you have to provide it when registering or updating the user.
profile: a “person” object. This is created automatically when you create a new user; don't try to add it yourself. Don't update this directly; update the person through its object endpoint.

---

But don’t know how i integrate(Registration/Login process) in iOS App. 

Regards
Shiju Varghese

**Comment by smscotten** [comment]
This, your other versions of this question you've made threads for, and the other threads you've tried to hijack, are questions about iOS development, and not at all specific to pump.io.

Every modern programming language (at least those for which you can do iOS development) has some form of support for making HTTP requests. So let me direct you to:

http://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods

…and to the documentation for the platform and/or language on which you're developing your app.

I'm sorry to be this blunt, but it's rather rude to post multiple threads with the same question and to hijack other topical threads with your unrelated question. These may explain why no one else has answered any of your queries. Furthermore, asking a question which is unrelated to the program in question is similarly off-putting. It is as if you were asking us how to defragment your hard drive. This isn't the place for it. 

I'm not trying to beat up on you here, just want to help you get answers to your future questions. Please take a look at [How to ask questions the smart way](http://www.catb.org/esr/faqs/smart-questions.html) by Eric Steven Raymond and Rick Moen. (I know, I'm violating the "reply to a first offender off-line" suggestion, but it isn't an option here. I certainly don't mean to publicly shame you.)

Good luck.
