### ISSUE TITLE
pump.io requires a version of bcrypt that is incompatible with recent nodejs

### ISSUE THREAD

**Issue by ayleph** [pump-io/pump.io#1071]
According to the [bcrypt package page](https://www.npmjs.com/package/bcrypt), node 0.11 and up require bcrypt 0.8.x. My distro (Arch Linux) currently packages node 0.12. package.json requires bcrypt 0.7.x, which is incompatible with recent nodejs versions. I modified my local package.json to use bcrypt 0.8.x, and so far everything seems okay.

**Comment by pangguoming** [comment]
i get that error also, can you help me? 
i get the following error:
gyp ERR! configure error 
gyp ERR! stack Error: ENOSPC, mkdir '/home/rainbow/WebstormProjects/pump.io-master/node_modules/bcrypt/.node-gyp'
gyp ERR! stack     at Error (native)
gyp ERR! System Linux 3.2.0-84-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rainbow/WebstormProjects/pump.io-master/node_modules/bcrypt
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.2.0-84-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rainbow/WebstormProjects/pump.io-master/npm-debug.log

**Comment by evanp** [comment]
For now use 0.10

**Comment by X4fyr** [comment]
Installation works for me when changing to bcrypt 0.8.x.
But npm test throws:

    > pump.io@0.3.0 test /srv/http/webapps/pump.io
    > vows test/*-test.js
    
    /srv/http/webapps/pump.io/node_modules/zombie/node_modules/jsdom/lib/jsdom/level1/core.js:418
      set nodeName() { throw new core.DOMException();},
                   ^
    SyntaxError: Unexpected token )
        at exports.runInThisContext (vm.js:73:16)
        at Module._compile (module.js:443:25)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/srv/http/webapps/pump.io/node_modules/zombie/node_modules/jsdom/lib/jsdom/level2/core.js:1:94)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
    npm ERR! Test failed.  See above for more details.

Haven't tested general functionality for now.
Installing node 0.10.0 in archlinux is a bigger task, because there where some changes since then (f.e. separating npm in a single package).

**Comment by ryanweal** [comment]
This issue killed my server unfortunately. We need to get pump.io running on a recent version of node again.

**Comment by strugee** [comment]
@ryanweal I've started working on this in [my fork][1], FWIW.

 [1]: https://github.com/strugee/pump.io

**Comment by strugee** [comment]
Closing as this has been fixed for a long, long time now
