### ISSUE TITLE
Retrieve JSON feeds of public profil

### ISSUE THREAD

**Issue by Safouane** [pump-io/pump.io#1075]
How can i retrieve public JSON feeds of any profile that shares public notes.
when i try that, i get this message : {"error":"Not logged in."}

**Comment by ShijuDekhDekh1** [comment]
Firstly you have to get ’Token’ and ’Secret Key’ with help of OAuth. You can get feeds using OAuth. Without OAuth you can’t do anything.
I made some api’s with the help pump.io. Hope it would be help you.

1. Get Feed : https://hostname/api/user/nickname/feed

2. Get Followers : https://hostname/api/user/nickname/followers

3. Get Lists : https://hostname/api/user/nickname/lists/person

4. Get Users: https://hostname/api/users

Regards
Shiju Varghese

**Comment by Safouane** [comment]
@Shiju thanks for the detailed response. 
What I have is a simple Android app that grabs Jason feed and print it into a listview. Can I do the same using OAuth?

**Comment by strugee** [comment]
@Safouane do you still need help? Or can I close this?
