### ISSUE TITLE
Login button disabled when using Midori browser

### ISSUE THREAD

**Issue by rfc2822** [pump-io/pump.io#1076]
When using Midori/0.5.9 (Javascript is enabled and working) with fmrl.me (don't know which pump.io version), I can't login because the login button stays disabled. Maybe related to #778.

The same happens in Firefox when the password is auto-filled (see issue #463), but it seems this has already been fixed in pump.io.

If you need further information, please let me know.

**Comment by strugee** [comment]
@rfc2822 why did you close this? Is it no longer reproducible?
