### ISSUE TITLE
Bad content type: text/html

### ISSUE THREAD

**Issue by bvolkmer** [pump-io/pump.io#1085]
Hey,
I face the following issue when trying to connect from clients like openfarmgame, identica etc.

```
Express
500 Error: Bad content type: text/html

at /opt/openfarmgame/models/host.js:127:22
at IncomingMessage. (/opt/openfarmgame/node_modules/dialback-client/lib/dialbackclient.js:208:21)
at IncomingMessage.emit (events.js:117:20)
at _stream_readable.js:929:16
at process._tickCallback (node.js:419:13)
```

And what the logs are saying:

```
[2015-06-21T17:59:41.571Z]  INFO: pump.io/web/502 on arkos:  (req_id=d7fffd4a-3e57-4429-ac6b-a1b31d5f1927, serverTime=5, req.remoteAddress=2a03:560:150::125, req.remotePort=58043)
GET /.well-known/host-meta HTTP/1.1
accept: application/json, application/xrd+xml; q=0.5
host: pump.x4fyr.de
connection: keep-alive
--
HTTP/1.1 200 OK
HTTP/1.1 200 OK
X-Powered-By: Express
Vary: Accept-Encoding
Server: pump.io/0.3.0 express/2.5.11 node.js/v0.12.4
Content-Type: application/json; charset=utf-8
Content-Length: 765
Date: Sun, 21 Jun 2015 17:59:41 GMT
Connection: keep-alive
--
client: {
  "title": "<none>"
}
```

Mind the `Content-Type: application/json`

That might be a problem with the ipv4 address.
My ISP just supports DSlite, meaning I have public IPv6 Addresses, but not IPv4. To surround this, I use feste-ip.net, where I got a IPv4 address, that forwards portwise to specified IPv6-Addresses.
But I can't test if there is something wrong whith this forwarding, since I don't know any pump.io instance that is IPv6 ready, so that I can try there.

My currently running instance at pump.x4fyr.de, you may try I you want.

Can someone say what the problem is, or at least know a IPv6 enabled pump.io instance, so that I can test?

Greetings

**Comment by X4fyr** [comment]
OK. Tested in an IPv6 pump.io resulting in the same error.

**Comment by strugee** [comment]
Hey @bvolkmer! Do you still experience this issue with a modern pump.io version?

**Comment by strugee** [comment]
Closing to keep our issue tracker clean.

If anyone is able to reproduce this with a modern version of pump.io, feel free to comment and I'll reopen.
