### ISSUE TITLE
Get rid of simplesmtp

### ISSUE THREAD

**Issue by strugee** [pump-io/pump.io#1118]
See #1113. `simplesmtp` is marked deprecated, so we should get rid of it.

**Comment by evanp** [comment]
Is there an equivalent?

**Comment by strugee** [comment]
Yeah, it's linked to on npm.

**Comment by profOnno** [comment]
[haraka](https://www.npmjs.com/package/Haraka)
[smtp-server](https://www.npmjs.com/package/smtp-server), same developer. 
> Create SMTP server instances on the fly. This is not a full-blown server application like Haraka but an easy way to add custom SMTP listeners to your app. This module is the successor for the server part of the (now deprecated) SMTP 

It can be done, but it's not a priority IMHO. It's only used for testing so no security issues. When we need different test cases which require more checking on newer mailservers that won't accept the mails as the are sent now, this priority will go up :arrow_up: .
