### ISSUE TITLE
How to specify dialback port?

### ISSUE THREAD

**Issue by h4ck3rm1k3** [pump-io/pump.io#1127]
How can we specify an alternative dialback port? If your pump is not running on port 80/443

**Comment by larjona** [comment]
I'm not sure I understand the question, but some info that may help (I hope):
https://github.com/e14n/pump.io#web-server-proxy
http://www.sjoberg.fi/blog/pumpio.html

**Comment by h4ck3rm1k3** [comment]
If you have two pump servers running how does the dialback know which to use? 
Thanks, I think that urlPort is what I need.

**Comment by strugee** [comment]
Can this be closed?
