### ISSUE TITLE
Use yargs for command-line options

### ISSUE THREAD

**Issue by evanp** [pump-io/pump.io#1202]
yargs is nice since it can handle a config file, environment variables, or command line args interchangeably. For systems like Docker using env vars is preferable.

**Comment by evanp** [comment]
https://www.npmjs.com/package/yargs

**Comment by strugee** [comment]
Blocked on yargs/yargs#695

**Comment by strugee** [comment]
Implemented in the `yargs` branch; will land to `master` tomorrow in time for the 4.0.0 beta release assuming Travis passes

**Comment by strugee** [comment]
Landed to `master` but still needs doc changes. Leaving open.

**Comment by strugee** [comment]
Doc changes landed yesterday and went out with beta 5.
