### ISSUE TITLE
Implement a super-simple script for installing pump.io

### ISSUE THREAD

**Issue by strugee** [pump-io/pump.io#1213]
I've been thinking for a while about having a dead-simple installation and setup program for pump.io. Such a program would be distributed through npm and would do things like:
- Fix npm (on Debian-based systems at least)
- Install pump.io
- Use sensible defaults for production (e.g. using `databank-mongodb` instead of `databank-disk`, using the correct ports, etc.)
- Acquire a TLS cert through Let's Encrypt
- Set up a systemd service for the pump daemon

Basically you'd give it your desired URL and whether you want to reverse proxy or not and it'd do the rest. We'd support it for 80-90% of use-cases and be conservative about what we set up (i.e. if something might break, we wouldn't do that thing - for example, messing with existing webserver configs). If anyone wanted to do something not supported, manual installation as we have now would always be an option.

Also, this would almost certainly be a project developed outside of core.

Thoughts?

**Comment by skellat** [comment]
If anything is built systemd-related, care must be taken to work around the denial of service issue that popped up recently.

See: 

https://github.com/systemd/systemd/issues/4234
https://www.agwa.name/blog/post/how_to_crash_systemd_in_one_tweet

Coping with systemd is essential but it presents unique issues of its own.

**Comment by strugee** [comment]
@skellat maybe I'm missing something, but I don't see how that's relevant. All we'd do is write a service file to `/etc/systemd/system`, and maybe enable and start said service via `systemctl`. None of that goes near the notify code.

**Comment by shaworth** [comment]
Docker isn't without it's problems, however as a wrapper around pump.io it works well.

**Comment by strugee** [comment]
@shaworth that's a separate issue: see #789

**Comment by strugee** [comment]
I'm not really interested in doing this anymore. Too much work and the things it automates either aren't that hard/are well-documented, or we're planning to pull it into core anyway (*coughcough* #1259)
