### ISSUE TITLE
Sharing a public post is not public

### ISSUE THREAD

**Issue by clacke** [pump-io/pump.io#1214]
I created https://pumprock.net/clacke/note/5W2IQNWERFK0WN9YQAUt0Q because of [#1216](https://github.com/pump-io/pump.io/issues/1216). This is my backup user. The note is public, and I can see it in https://pumprock.net/clacke/ when anonymous.

Then I shared the post as clacke@microca.st .

Expected result: The post is visible to anonymous users in the stream at https://microca.st/clacke .

Actual result: Only logged-in people (followers?) seem to be able to see it.

What's more surprising is that I have shared other posts, by other users, and those are visible when anonymous users browse my stream. But none of my clacke@pumprock.net posts seem to be.

**Comment by strugee** [comment]
I believe this is an addressing issue. What client did you use to share the pumprock post? Do you remember which client you used to share the available-anonymously shares?

**Comment by clacke** [comment]
I believe Web UI for both, but I will try to verify if sharing other posts in the Web UI makes them hidden. Do you think this is related to https://github.com/pump-io/pump.io/issues/1216 ?

**Comment by strugee** [comment]
Thanks.

Re: #1216, _possibly_, but I doubt it.

**Comment by clacke** [comment]
It seems you are right. Sharing in the Web UI breaks the _Public_ addressing. Everything I can see on https://archive.is/I6IWr is probably shared using _AndStatus_.

**Comment by jankusanagi** [comment]
Sharing "Cc: Followers" is the standard thing to do. So we could say that the issue you found, is by design.

A client can customize the addressing, but not doing so is not a bug per se.

**Comment by clacke** [comment]
I see the point. If I don't want the general public to see my posts, I wouldn't want them to see what I share either, regardless of the access attributes of the shared posts. Fixing this would mean adding UI for changing default post access.

That makes this a duplicate of [#364](https://github.com/pump-io/pump.io/issues/364). Closing.

**Comment by strugee** [comment]
Closing as this isn't a bug, just symptomatic of a larger problem - the fact that the way share addressing interacts with the addressing of the original post isn't particularly intelligent.
