### ISSUE TITLE
Expired certificate on e14n.com makes the pump.io website painful/scary to browse

### ISSUE THREAD

**Issue by gasche** [pump-io/pump.io#1223]
Hi,

The [official pump.io website](http://pump.io/) has a news to a [Security Alert](https://e14n.com/evan/note/m0B0MlAySEiC8ey4aQ6nPA) that is hosted on e14n.com, and my browser prevents me from visiting it (easily) as the certificate is expired since 10/21/2016. For a better potential-user experience, would it be possible to get a correct certificate, or host the content on the same domain?

**Comment by strugee** [comment]
Thanks for pointing this out; I just sent mail to Evan letting him know.

Unfortunately there isn't much else we can do.

**Comment by strugee** [comment]
e14n.com has been down for a while and I believe @evanp has switched to just using identi.ca anyway. Plus the XSS thing hasn't been on the homepage for a long time. Closing.
