### ISSUE TITLE
DANE support

### ISSUE THREAD

**Issue by strugee** [pump-io/pump.io#1224]
As suggested in #1061.

I'm actually against this, but I promised I'd file followups and we should have a proper discussion about it anyway.

**Comment by clacke** [comment]
Curious why you're against it.

**Comment by strugee** [comment]
@clacke DANE is seriously crippled without DNSSEC, which has significant design flaws that mean it's not actually a whole lot better than the CA system: https://youtu.be/xIiklPyS8MU?t=29m30s

I'm not interested in adding significant complexity to the code when it has questionable benefits, especially since DNSSEC/DANE has little to no adoption. (Note also that Chrome used to have DANE support and dropped it for reasons similar to the above.)

**Comment by strugee** [comment]
If you have time to look for the Chrome mailing list threads where that change was discussed, btw, the arguments are highly educational.

**Comment by strugee** [comment]
Closing as there hasn't been activity on this in a year and I'm just as against it as I was when it was opened.

If anyone has compelling arguments in favor of DANE feel free to leave them here and I can reopen.
