### ISSUE TITLE
Move to pure Javascript bcrypt

### ISSUE THREAD

**Issue by evanp** [pump-io/pump.io#1233]
The compiled bcrypt is a pain; we should just use https://www.npmjs.com/package/bcryptjs which is slower but pure JS.

**Comment by strugee** [comment]
@evanp why? I've never had any problems with it (at least not since we upgraded it for newer Node versions)

**Comment by strugee** [comment]
Also, AFAICT, this will have a performance impact due to existing hashes unless we do some sort of sketchy migration when users use their password in any way since bcryptjs is (according to its README) ~2.7x slower

**Comment by strugee** [comment]
Per the meeting last week we're going to take the perf hit here since it doesn't happen very frequently. This'll make it into the next release probably.
