### ISSUE TITLE
tryit page hanging

### ISSUE THREAD

**Issue by bassdeveloper** [pump-io/pump.io#1246]
This URL is not responding: http://pump.io/tryit.html

Message : Waiting for hotpump.net

**Comment by jankusanagi** [comment]
Yes, that's what happens when one of the servers, selected at random from the "try" list, is down.
In this case, hotpump.net is down at the moment.

You could clear the cookies for the pump.io domain and try again.

**Comment by strugee** [comment]
Heya! Thanks for taking the time to report a bug. As @jankusanagi mentioned, there isn't a lot we can do about this except wait for hotpump.net to come back up. :/

Therefore I'm closing this issue since there's nothing else to do. But again - thank you for taking the time, we appreciate it!
