### ISSUE TITLE
Use a general data directory instead of `uploaddir`

### ISSUE THREAD

**Issue by strugee** [pump-io/pump.io#1261]
The fact that uploads are stored directly in `uploaddir` is problematic because if we want to store anything else on disk - e.g. #1259 would need this to store certificates and keys, #1260 might use this to store OCSP responses, etc. - we don't know where to put that stuff unless we want to put it directly in `uploaddir` and add logic to ignore requests for it, which is a terrible idea, obviously.

Instead we should have admins designate a directory that pump will store general "state" in. Uploads would go to `$statedir/uploads`, Let's Encrypt keys would go to `$statedir/keys`, etc.

To implement this, we would:

1. Start recognizing a `datadir` (name TBD) option
2. Modify the uploads code to read/write from/to an `uploads` subdirectory of the data directory
3. Add an `enableUploads` option that would control whether uploads are allowed or not
4. Error if the admin specified an `uploaddir`

Upon upgrade, existing admins would be required to:

1. Remove their `uploaddir` option
2. Set an appropriate `datadir` option
3. Move the former `uploaddir` into the `datadir`, renaming it `uploads` if they hadn't already

We _could_ do most (all?) of this automatically, but it seems hacky and prone to breakage. Better to just let the admin do their thing.

**Comment by strugee** [comment]
Another reason to do this: if we ever move to something Linked Data Signatures we'll need a place to store long-term private identity keys

**Comment by strugee** [comment]
This change is ready to merge from the `uploaddir-to-datadir` branch.

**Comment by strugee** [comment]
This got merged a while ago.

**Comment by evanp** [comment]
Do it automatically. Don't put this burden on the admin. Especially when the admin is me.

**Comment by strugee** [comment]
@evanp would a shell script be sufficient?

**Comment by strugee** [comment]
@evanp there's a script for this now at https://github.com/pump-io/pump.io/blob/master/util/migrate-uploaddir.sh. It's suitable for `curl | bash` if that's convenient (`curl -L https://git.io/vSJ6y | sudo bash` will do the trick)
