### ISSUE TITLE
pump.io related servers may need an update

### ISSUE THREAD

**Issue by moshpirit** [pump-io/pump.io#1265]
The [pump.io related servers wiki section](https://github.com/pump-io/pump.io/wiki/Servers#pumpio-related-servers) may need an update because pumpiostatus.website (like some other servers like 1realtime.net or pumpity.net) is down (I'm reporting this because I'm not sure if it's a temporary downstate or if it's definitive).

Also, ofirehose.com doesn't show any info either (and as far as I remember it should show some "public posts" or something like that, right? and ragtag.io is in sale.

**Comment by strugee** [comment]
A lot of these have been down semi-permanently but we'd like to bring them back at some point. pumpstatus.website, however, is gone for good, so I went ahead and removed that one. Thanks for the report.

**Comment by moshpirit** [comment]
Thanks for the reply! :)

**Comment by moshpirit** [comment]
Sorry to bother again but which servers and what do you mean with semi-permanently down? do you know how long are 1realtime.net or pumpity.net going to be down? Cause I couldn't find any information anywhere and I have my main account on 1realtime.net.

**Comment by strugee** [comment]
@moshpirit a lot of the servers on that page, including 1realtime.net and pumpity.net, are run by @evanp. There isn't a lot I (or anyone else active in the project these days) can tell you re: how long they'll be down - the best answer is "they'll be back whenever Evan has time." So by "semi-permanently down" I mean that in theory they'll come back up at some point, but in the meantime they've been down for a long time and we don't really know when they'll be back.
