### ISSUE TITLE
Realtime seems to not work.

### ISSUE THREAD

**Issue by ambrt** [pump-io/pump.io#1266]
I installed pump.io globally via npm  on Ubuntu VM .
I can access "Awesome Sauce" UI and creating/following is working.

But one thing that doesn't seem to work is realtime notifications.
I get notification in upper right part,  only when i refresh page with F5.

In console there is error:

> GET http://myserver/main/realtime/sockjs/info 404 (Not Found)

I also installed globally `sockjs`.
What can i do?

**Comment by strugee** [comment]
Are you reverse proxying? Give us your `pump.io.json`.

**Comment by strugee** [comment]
> I also installed globally `sockjs`.

You do not need to do this; sockjs is already installed as a dependency.

Please also give us your pump.io version, install method, and Node.js version. Basically, generally be as detailed as possible.

**Comment by ambrt** [comment]
Node version:

> v6.9.4

Npm version:

> 3.10.10

Pump.io installed via:

> sudo npm install -g pump.io

Pump.io version:

> pump.io@2.1.0


pump.io.json ( at ~/.pump.io.json )
```
{
    "driver":  "memory",
    "params":  {"dir": "/tmp/pumpio/"},
    "secret":  "my dog has fleas",
    "noweb":  false,
    "site":  "Awesome Sauce",
    "owner":  "Awesome Inc.",
    "ownerURL":  "http://example.com/",
    "port":  80,
    "hostname":  "stream1.dev",
    "nologger":  false,
    "serverUser":  "me",
    "uploaddir": "/var/local/pump.io/uploads",
    "debugClient": true,
    "firehose": "ofirehose.com",
    "sockjs": true
}
   
```
stream1.dev is a domain pointing to this VM ip address : 

> 192.168.119.128


Starting log:

> {"name":"pump.io","hostname":"ubuntu","pid":14373,"level":30,"msg":"Listening on 80 for host stream1.dev","time":"2017-01-17T16:48:19.021Z","v":0}

Error log when accessing `http://stream1.dev/main/realtime/sockjs/info` from outside of VM (from host of VM)
```
{
  "name": "pump.io",
  "hostname": "ubuntu",
  "pid": 14640,
  "req_id": "a4305db3-96b3-4ea4-82e0-cee67df31523",
  "component": "web",
  "level": 30,
  "req": {
    "method": "GET",
    "url": "\/main\/realtime\/sockjs\/info",
    "headers": {
      "host": "stream1.dev",
      "connection": "keep-alive",
      "cache-control": "max-age=0",
      "upgrade-insecure-requests": "1",
      "user-agent": "Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/55.0.2883.87 Safari\/537.36 OPR\/42.0.2393.94",
      "accept": "text\/html,application\/xhtml+xml,application\/xml;q=0.9,image\/webp,*\/*;q=0.8",
      "accept-encoding": "gzip, deflate, lzma, sdch",
      "accept-language": "en-US,en;q=0.8",
      "cookie": "connect.sid=s%3AmGPFjJUjuoXCPiCO18TmPeCiZKSuvnZO.GAyWcAYQ1MD4BNqUDdN75lODITdixUdpEL2OLqWgjME"
    },
    "remoteAddress": "192.168.119.1",
    "remotePort": 55851
  },
  "res": {
    "statusCode": 404,
    "header": "HTTP\/1.1 404 Not Found\r\nX-Powered-By: Express\r\nServer: pump.io\/2.1.0 express\/3.21.2 node.js\/v6.9.4\r\nContent-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' cdnjs.cloudflare.com ajax.googleapis.com; style-src 'self' 'unsafe-inline' cdnjs.cloudflare.com; img-src *; object-src 'none'; media-src *; child-src 'self' www.youtube.com; frame-ancestors 'none'; plugin-types 'none'\r\nX-Frame-Options: DENY\r\nX-Download-Options: noopen\r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: 1; mode=block\r\nContent-Type: text\/html; charset=utf-8\r\nContent-Length: 38\r\nVary: Accept-Encoding\r\nDate: Tue, 17 Jan 2017 16:53:16 GMT\r\nConnection: keep-alive\r\n\r\n"
  },
  "serverTime": 336,
  "client": {
    "title": "<none>"
  },
  "msg": "",
  "time": "2017-01-17T16:53:16.303Z",
  "v": 0
}
```

**Comment by ambrt** [comment]
I made new VM, installed python-dev, nodejs, graphicsmagick, pump.io via npm,
same .pump.io.json and error still occurs.

**Comment by strugee** [comment]
@ambrt yeah, that error's unrelated. Just fixed it in master. You should probably also use a Databank driver other than `memory`, and you should change the `secret` value.

WRT your original problem, that's super weird. I can reproduce on pump.strugee.net, will investigate further; I suspect this is a regression in the 2.x series since identi.ca is running 1.0.0 and this works there.

**Comment by ambrt** [comment]
In long run i planned to use databank-mongodb, so memory driver is just for checking pump.io out.
I'll change the secret, too.

**Comment by strugee** [comment]
This is now fixed in master. Leaving this issue open as I'd like to do a patch release since this is a pretty big regression.

**Comment by strugee** [comment]
2.1.1 just went out to npm.
