### ISSUE TITLE
pump.io 3.0.0-alpha.0: Trying to OAuth to server makes it crash

### ISSUE THREAD

**Issue by clacke** [pump-io/pump.io#1281]
```
$ curl -\# -i 'https://pump.strugee.net/main/authorized/datamost.com'|head -n 3

curl: (52) Empty reply from server
$ curl -\# -i 'https://pump.strugee.net/'|head -n 3

curl: (7) Failed to connect to pump.strugee.net port 443: Connection refused
$ curl -\# -i 'https://pump.strugee.net/'|head -n 3
######################################################################## 100.0%
HTTP/1.1 200 OK
X-Powered-By: Express
Server: pump.io/3.0.0-alpha.0 express/3.21.2 node.js/v4.7.2
```

**Comment by strugee** [comment]
I don't use curl - what do the `-i` and `-#` options do?

**Comment by strugee** [comment]
Reopening because this is high-impact and I intend to backport it.

**Comment by strugee** [comment]
4.1.1 with backported fix went out this morning.

**Comment by clacke** [comment]
You rock!

Sorry for not replying earlier. I have cleaned up my github notifications deluge since then. :-)

For the sake of future people reading this:

 * `curl -#` just affects the progress bar format -- without it the output is a table of all kinds of perf feedback
 * `curl -i` makes it show server headers

**Comment by strugee** [comment]
@clacke no problem! Just happy it's fixed :D
