### ISSUE TITLE
Resubmit Dialback authentication IETF draft

### ISSUE THREAD

**Issue by strugee** [pump-io/pump.io#1285]
https://datatracker.ietf.org/doc/draft-prodromou-dialback/ is a thing but it expired. It'd be nice if we could push this forward again and get it standardized. (This would probably also be relevant for the ongoing ActivityPub work.)

**Comment by evanp** [comment]
Do we need it? Aren't there other OAuth 2.0 standards that do the same thing?

**Comment by strugee** [comment]
Dunno. This was from a while ago, things were different then. Lots of the auth stuff, and the AP spec itself to a certain extent, was still in flux. 

Feel free to close, I'd be fine just dropping this on the floor. I think you said it wasn't worth it at some point anyway.

**Comment by strugee** [comment]
ActivityPub is the future, not this protocol Evan made up 5 years ago :thumbsup:
