### ISSUE TITLE
Install Error on Ubuntu 14.04

### ISSUE THREAD

**Issue by a2t2** [pump-io/pump.io#1309]
I'm trying to install pump.io on a Ubuntu 14.04 machine and I'm observing install errors. I notice the github status says "build failing", but I wanted to share the errors I'm facing (I tried to install by cloning via git, as well as, installing via tar version 2.0.3.x from the website). 

After cloning the git or unpacking the tar, I install using "npm install". The environment setup includes:
node.js version: 6.10.1
npm version: 3.10.10

During the install, the errors are:

```
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.2.0-27-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/pump.io/node_modules/bufferutil
gyp ERR! node -v v6.10.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
In file included from ../node_modules/nan/nan.h:82:0,
                 from ../src/validation.cc:15:

make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.2.0-27-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/pump.io/node_modules/utf-8-validate
gyp ERR! node -v v6.10.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN lifecycle pump.io@4.0.0-alpha.0~postinstall: cannot run in wd %s %s (wd=%s) pump.io@4.0.0-alpha.0 npm run build /var/www/pump.io
npm WARN lifecycle pump.io@4.0.0-alpha.0~prepublish: cannot run in wd %s %s (wd=%s) pump.io@4.0.0-alpha.0 npm run build /var/www/pump.io
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.1.0 (node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.1.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.1.0 (node_modules/utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.1.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

When I try to test using "npm test", I observe the following in the end:

```
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at Object.<anonymous> (/var/www/pump.io/test/lib/app.js:28:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/pump.io/test/test-lib-oauth-test.js:26:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
npm ERR! Test failed.  See above for more details.
```

If you think the errors could be specifically due to my system setup, please let me know.

**Comment by strugee** [comment]
@a2t2 fixed the formatting of your issue; hope that's okay.

> I tried to install by cloning via git, as well as, installing via tar version 2.0.3.x from the website

Sorry, we really don't recommend installing via the archives that GitHub provides (which is what you got from the website's sidebar). I've removed them to prevent future confusion - thanks for the reminder.

The "errors" during your install are cosmetic. As you can see at the end, npm tried to install an optional dependency and failed. Since it's optional, it really doesn't matter.

The "undefined" error, however, is a problem with git master right now. I've seen it in CI and hope to find time to fix it in the next day or two.

What exactly are you trying to accomplish? Are you trying to set up the codebase to develop pump or are you trying to set up a node on the pump network?

**Comment by a2t2** [comment]
I am new to using pump.io. My goal was to setup an instance of pump.io on my own web server, so it can be accessed via the browser, and via open source apps like AndStatus.

**Comment by strugee** [comment]
@a2t2 OK. You shouldn't be installing from git master then. I would **strongly** recommend installing via npm. What Linux distribution are you using? If it's Debian we have a guide here: https://pumpio.readthedocs.io/en/latest/sysadmins-debian.html

**Comment by a2t2** [comment]
I'm using a Ubuntu 14.04 setup. Will the steps be the same ? Is there any tutorial specific to Ubuntu ?

**Comment by strugee** [comment]
No, nothing specifically for Ubuntu. We have a bug open but you should be able to just use the Debian instructions

**Comment by strugee** [comment]
Feel free to reach out if you need help too. https://github.com/pump-io/pump.io/wiki/Community

**Comment by a2t2** [comment]
I have installed pump io based on the instructions for Debian. I am first trying to test it in a Ubuntu 14.04 VM. This VM also has Apache installed, as I have other web applications running. Without pump io in the enabled folder, nginx can reload and restart correctly. Once pump io's config is put in place in sites-available folder, nginx fails to restart. It has to be an error somewhere in the pumpio config. 

The configuration I am trying to put in place:

nginx default HTTP port: 70
pumpio HTTP request port: 8080
pumpio SSL request port: 445

Since I'm testing in the VM, I put the following entry in my /etc/hosts. For actual deployment, the domain name will change.
`127.0.0.1	  www.pumpio.com`

With the given files, restarting nginx shows the error (in /var/log/nginx/error.log):
`bind() to 0.0.0.0:80 failed (98:Already is use)`

Also, as mentioned in the installation steps for Debian, when I test the installation, the information displayed is incorrect based on the desired config (I don't know why it listens on port 31337):
`$ sudo -u pumpio pump
{"name"="pump.io", "hostname":"localhost","pid":19689,"level":30,"msg";"Listening on 31337 for host 127.0.0.1 ... }`

I've attached the relevant files. 
[/etc/nginx/nginx.conf](https://github.com/pump-io/pump.io/files/886058/nginx.conf.txt)
[/var/lib/pump/.pumpio.json](https://github.com/pump-io/pump.io/files/886067/pump.io.json.txt)
[/etc/nginx/sites-available/default](https://github.com/pump-io/pump.io/files/886049/default.txt)
[/etc/nginx/sites-available/pump](https://github.com/pump-io/pump.io/files/886075/pump.txt)


Please help me configure pumpio. Thanks.

**Comment by strugee** [comment]
> For actual deployment, the domain name will change.

I'm a little unclear as to what you're trying to do here, but please make sure you read and understand https://github.com/pump-io/pump.io#making-changes.

As for your Nginx problems, the config is failing because Apache is already using port 80. This is the error in your logs. You should probably just have Apache proxy back to pump (in the same way that Nginx does). You'll have to disable realtime support, though, which can't function under Apache.

Please show me `grep pump /etc/passwd`.

**Comment by a2t2** [comment]
> config is failing because Apache is already using port 80
My nginx is configured to use port 70, then why does it have a problem with port 80 ? I can try to disable Apache's use of port 80.

> Please show me grep pump /etc/passwd
pumpio:x:998:1001::/var/lib/pumpio:

> You should probably just have Apache proxy back to pump (in the same way that Nginx does)
This is my first time configuring nginx alongside Apache. If you can recommend a tutorial for this step, it will be helpful.

**Comment by strugee** [comment]
> My nginx is configured to use port 70, then why does it have a problem with port 80 ? I can try to disable Apache's use of port 80.

It must not be properly configured for port 70. It's the only explanation I can think of. In order to diagnose your problem I'd have to look at the nginx config, but I'm not bothering because:

> This is my first time configuring nginx alongside Apache. If you can recommend a tutorial for this step, it will be helpful.

You misunderstood my suggestion :)

I meant: forget about nginx and just use Apache, since that's what you already have set up. We don't currently have instructions for configuring Apache (I opened [an issue][] in our docs repo) but basically you just need to proxy incoming requests back to the pump daemon listening on some high-numbered port on localhost. I'm guessing you can figure this out based on your configs for other webapps you run, as well as what's in the nginx configuration, but let me know if you need help.

**Comment by a2t2** [comment]
I retried the installation on a clean Debian Jessie VM. The VM does not have apache.
The installation went through, but I am facing an issue when I try to start pumpio using `sudo -u pumpio pump`. I see the following error being printed repeatedly:

`Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Object.createSecureContext (_tls_common.js:67:17)
    at Server (_tls_wrap.js:772:25)
    at new Server (https.js:24:14)
    at Object.exports.createServer (https.js:44:10)
    at Function.<anonymous> (/usr/lib/node_modules/pump.io/lib/app.js:225:31)
    at next (/usr/lib/node_modules/databank-mongodb/node_modules/step/lib/step.js:51:23)
    at Function.<anonymous> (/usr/lib/node_modules/databank-mongodb/lib/mongodb.js:110:25)
    at next (/usr/lib/node_modules/databank-mongodb/node_modules/step/lib/step.js:51:23)
    at /usr/lib/node_modules/databank-mongodb/node_modules/step/lib/step.js:83:14
/usr/lib/node_modules/databank-mongodb/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });`

It seems to be an error related to certificates. My .crt and .key files do have the appropriate `--- BEGIN` lines. Can you suggest a way to solve this ? Thanks.

**Comment by strugee** [comment]
Hmm, yeah. Definitely related to TLS key material.

Are you sure you're pointing pump to the right files, and that the `pumpio` user can access them?

**Comment by a2t2** [comment]
I realized my mistake. In the tutorial (https://pumpio.readthedocs.io/en/latest/sysadmins-debian.html), the key and cert mappings are mentioned in reverse in the example:

> "key":  "/path/to/your/ssl-cert.crt",
    "cert":  "/path/to/your/ssl-cert.key"

I swapped them around, and now the site is working inside the VM.

Is there any admin account for pumpio ? It says registration disabled for new users.

**Comment by a2t2** [comment]
I figured out the flag in the json file for user registration.

I need to ask one last question related to port forwarding. Right now pumpio's config is for ports 8080 and 443 inside the VM. The VM externally has a port 8040, and I can setup port forwarding to allow host port 8040 to be forwarded to guest port 443. So from outside the VM, I would attempt to access the pumpio instance as:

> https://mydomain.example.com:8040

The problem is then when use a URL like above in the browser, the request gets redirected to `https://mydomain.example.com` and the website is not reached. I want to ask how would you suggest changing the `sites-available/pump` file to handle the above scenario.

**Comment by strugee** [comment]
@a2t2 huh, looks like a bug in the docs! Want to [submit a Merge Request][gitlab] to fix it? :)

There's no admin account. Guess you found how to enable registration.

 [gitlab]: https://gitlab.com/pump.io/pump-docs/


> I want to ask how would you suggest changing the sites-available/pump file to handle the above scenario.

Have Apache serve `mydomain.example.com` and use `ProxyPass`, etc. directives. If you paste your Apache config I can tell you more about what's going on.

**Comment by a2t2** [comment]
I am using the default nginx and pumpio configuration as mentioned on the Debian installation page. The VM does not have Apache. Based on the default settings in the tutorial, how would you suggest to fix the redirection issue related to port forwarding.

________________________________

**Comment by strugee** [comment]
@a2t2 so you're running a VM with nginx and pump.io inside, right? What's running on the host?

It sounds like what you're trying to do is get pump.io to run on port 8040 all the time. In general this is a very bad idea and I would strongly advise against it. Things will break.

**Comment by a2t2** [comment]
> so you're running a VM with nginx and pump.io inside, right? What's running on the host?
Yes that's correct. The host is Ubuntu machine.

> It sounds like what you're trying to do is get pump.io to run on port 8040 all the time
 My requirement is that inside the VM, pumpio should use 443, and the VM should port forward host port 8040 to guest port 443. My current restriction is that I need to setup this way. I have setup other web applications in similar way as well using port forwarding (usually the web app's hostname or server name config needs to be changed). Please advice on how to configure this pumpio instance.

**Comment by strugee** [comment]
OK. But you would be better having something on the host listen to port 443, and then just forward requests to pump on to the VM. Then you could make pump run on port 443 on the public Internet, too.

IIRC you can disable the redirection behavior by specifying `"redirectToCanonical": false` in your configuration JSON. But I want to be clear: I would _**strongly**_ recommend against this. I can't guarantee that things won't break if you try to federate with other instances (and if you report bugs I may or may not close them as won't fixes as we don't really try to support this configuration on public nodes). Additionally you will not be able to change your mind about the port later. You will be stuck with it unless you change (sub)domains, possibly forever. Please read https://github.com/pump-io/pump.io#making-changes again.

Again, this is not a good idea. I'd really recommend putting in some extra time now to get it right to begin with.

(As a side note, since pump is the only thing running in the VM you might as well remove Nginx and have pump bind directly to port 443. There's no reason you need Nginx since nothing besides pump wants port 443.)

**Comment by a2t2** [comment]
I have forwarded host's 443 to guest 443.

I am trying to test the instance in an isolated network. For apps like andstatus, they try to access the URL, say, `https://yourdomain.com/api/client/register`. When I try to login from the browser and try to goto such a URL, I get the response:

> error: Unknown type: client

I then tried to do the same with AndStatus and Puma (I hardcoded `/etc/hosts` on my test device), and I get the same response.
Can you please tell what does this error mean ?

**Comment by strugee** [comment]
Neat. Sorry to be harsh, it's just much easier in general if you do it right the first time :)

As for the error, I don't know. Paste your pump.io server logs.

Re: commandline tools, those are mostly just sample applications. You don't need them to use AndStatus.

**Comment by a2t2** [comment]
AndStatus is now working. I made a mistake with the login id (I put an incomplete sitename).

Regarding an observation when logging in from AndStatus or Puma, I notice a web page is launched to do OAuth. On the other hand, when I test AndStatus with other social networks like GNUSocial, it can do so without OAuth. Is authentication for pumpio from AndStatus possible without OAuth i.e. just by credentials sent in a POST request to server ?

**Comment by strugee** [comment]
> AndStatus is now working. I made a mistake with the login id (I put an incomplete sitename).

Gotcha. Perhaps report an AndStatus bug to handle this better?

> Is authentication for pumpio from AndStatus possible without OAuth i.e. just by credentials sent in a POST request to server ?

Nope. OAuth 1.0 is the only supported way to do authentication. This is unlikely to change, at least in the medium-term, as one of the problems with StatusNet (now GNU Social) was that it had a bunch of different ways to authenticate to it which ended up just being feature creep.

**Comment by strugee** [comment]
Unless you have any other questions, is it okay if I close this issue?

**Comment by a2t2** [comment]
Yes sure. Please go ahead and close the issue. The installation is working now. Thanks for your help !

**Comment by strugee** [comment]
Sure thing. Thanks for checking out pump.io!
