### ISSUE TITLE
Improve documentation for sample application CLI tools

### ISSUE THREAD

**Issue by ian-kelling** [pump-io/pump.io#1316]
What is an app in this context? This is the next section after running the daemon, it reads like this is the next and required step for using the pump.io server, is it? What does the app name signify? What possible values can it be? It says "the credentials file", as if the reader is supposed to know what that means or what it's used for, but they don't. What is the purpose of credentials here? Then it says "the clientID", what is that? It needs an explanation.

The command line documentation has contradicting documentation:

    Usage: /usr/bin/nodejs ./bin/pump-register-app -t title -e email [-w|-n]

The cli documentation seems to imply that port might be an important argument.

I tried some variations and got failures:

    ./bin/pump-register-app  -t web -e root@localhost -p 8000
    SyntaxError: Unexpected token < in JSON at position 0
        at Object.parse (native)
        at Function.<anonymous> (/home/ian/pump.io/bin/pump-register-app:80:25)
        at next (/home/ian/pump.io/node_modules/step/lib/step.js:51:23)
        at IncomingMessage.<anonymous> (/home/ian/pump.io/lib/pumpclient.js:141:13)
        at emitNone (events.js:91:20)
        at IncomingMessage.emit (events.js:185:7)
        at endReadableNT (_stream_readable.js:974:12)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by strugee** [comment]
Good question. Basically `pump-register-app` registers a client app for use with the pump server. Normally if you use a client like e.g. Dianara or Pumpa it will do this for you. The commandline tools in this repo are basically intended to be examples of applications.

That being said they're probably somewhat busted, as you're finding out. I'll push a fix to the README to make it less confusing and leave your issues open as something to fix in the future - but don't hold your breath. Thus far there have been more pressing things in the core, and that'll probably continue to be the case for a while.

Thanks for checking out pump :)

**Comment by strugee** [comment]
See also #1200

**Comment by strugee** [comment]
Moved to https://gitlab.com/pump.io/pump-docs/issues/14
