### ISSUE TITLE
New server, 404 on *.jade.js 

### ISSUE THREAD

**Issue by ian-kelling** [pump-io/pump.io#1318]
New server, main page works fine, go to login or register, I get 404s on urls like this:

http://localhost:5233/template/nav-loggedin.jade.js

Spinning wheel, page does not load. Not sure how to fix this.

Using git version of pump.io

**Comment by strugee** [comment]
Run `npm run build` to build templates.

**Comment by strugee** [comment]
Filed https://gitlab.com/pump.io/pump-docs/issues/5 about documenting this. Let me know if you have other problems.
