### ISSUE TITLE
"logfile" option has no apparent effect

### ISSUE THREAD

**Issue by ian-kelling** [pump-io/pump.io#1320]
In my pump config, I have

    "logfile": "/tmp/pump.io.json",

I do not have `nologger` in my config. pump logs to the console just like if I did not have logfile set. `/tmp/pump.io.json` is not created at all. I'm using pump from git, 464668b2fc.

**Comment by ian-kelling** [comment]
All of a sudden, this is not happening anymore. Could be user error, but I could have sworn I double checked.

**Comment by strugee** [comment]
Huh, weird! Feel free to reopen if it comes back (or ask in `#pump.io`)
