### ISSUE TITLE
SSL Usage

### ISSUE THREAD

**Issue by cyberfarer** [pump-io/pump.io#1329]
Greetings,

My installation works fine without SSL. But when I enable SSL, and I update my profile, the update fails and I get "An error occurred" banner across the top of the page. It appears to be related to XSS protection. The log reads as shown:

`Express\r\nServer: pump.io/3.0.1 express/3.21.2 node.js/v4.8.2\r\nX-Frame-Options: DENY\r\nX-Download-Options: noopen\r\nX-Content-Type-Options: nosniff\r\nX-XSS-Protection: `

My config is as shown:

`{

    "driver":  "mongodb",

    "params": {"host":"localhost","dbname":"pumpio"},

    "address": "192.168.10.105",

    "hostname":  "pump.domain.com",

    "port": 8444,

    "key": "/srv/pumpio/certs/pump.key",

    "cert": "/srv/pumpio/certs/pump.crt",

    "noweb":  false,

    "site":  "pump.domain.com",

    "secret": "Somethingelseentirely",

    "owner":  "Testing ",

    "ownerURL":  "http://www.doman.com/",

    "nologger": false,

    "logfile": "/var/log/pumpio/pumpio.log",

    "serverUser":  "pumpio",

    "enableUploads": "true",

    "datadir": "/srv/pumpio/uploads/",

    "debugClient": true,

    "disableRegistration": true,

    "ofirehose": "ofirehose.notused",

    "noCDN": true,

    "requireEmail": false,

    "compress": true,

    "smtpserver": "localhost",

    "proxyWhitelist": ["avatar3.status.net", "avatar.identi.ca", "secure.gravatar.com"]

}
`
Any assistance is appreciated.

**Comment by strugee** [comment]
The log you have provided is not enough and is cut off. Please provide the server log at the time the error occurs, as well as a couple lines before that for context.

Please also read https://pumpio.readthedocs.io/en/latest/sysadmins-faq.html#stuff-in-my-brand-new-account-randomly-doesn-t-work and https://github.com/pump-io/pump.io/blob/master/README.md#making-changes.

Cheers!

**Comment by strugee** [comment]
It will also really help if you can tell us the real domain name you're using. You can /msg it to me on Freenode IRC if you want (I'm strugee there too).

**Comment by strugee** [comment]
@cyberfarer ping?

**Comment by strugee** [comment]
@cyberfarer I'm closing this to keep our issue tracker clean. If you still need help, please provide the information I requested and I'd be happy to reopen.

Thanks for checking out pump.io!
