### ISSUE TITLE
Publish the Docker image to Docker Hub

### ISSUE THREAD

**Issue by strugee** [pump-io/pump.io#1418]
We need a security support plan for this. @JanKoppe are you okay with me publishing the official image?

**Comment by strugee** [comment]
So the rough plan is to regenerate Docker images on a cronjob and diff them with the old one. If there's a difference, they'll be published. We'll also provide nightly builds for git master users.

**Comment by strugee** [comment]
Ref #789

**Comment by JanKoppe** [comment]
AFAIK you should be able to just blindly build and push the images. Docker will compare the layer hashes before uploading, so if there are no changes nothing will be uploaded. Can be automated easily with Travis for example. Do you want me to work on this?

Also: Yes, of course you can push an image from the Dockerfile that I provided!

**Comment by strugee** [comment]
https://github.com/coreos/clair

@JanKoppe sorry, just saw this comment! You can work on it if you want but currently I'm stalled as the default build doesn't actually work for me on my (now-former) macOS laptop? I should try again now that I'm on a Linux machine but when I tried it last time I just got a weird empty response from the server (i.e. the server just closed the connection immediately before my HTTP request even went through).

**Comment by JanKoppe** [comment]
That is very strange. I just built the current master branch on my machine and spun up a pump instance with the docker-compose configuration. Seems to work just fine. Not sure if this was some quirk with running Docker on macOS (in a VM).

**Comment by strugee** [comment]
Yeah, super weird. It's happening on Linux too.

You said you're just using Docker Compose? I've been invoking with `sudo docker run -p 127.0.0.1:31337:31337 1d337c18ac13`, maybe that's it...

**Comment by JanKoppe** [comment]
Are you attaching a mongodb instance to that container? The container just by itself should not be running right. Any log output available? That's some really strange behaviour.

Please try it again with the compose file - it launches a mongodb instance as well and configure pump to use that instance.

**Comment by Serkan-devel** [comment]
Will there be multi-arch docker images for arm (Raspberry Pi) too?

**Comment by Serkan-devel** [comment]
There are issues with mongodb though

**Comment by Serkan-devel** [comment]
Could it use Redis instead of mongodb?

**Comment by strugee** [comment]
File another bug, please

**Comment by strugee** [comment]
5.1.1 includes infrastructure to push official images to Docker Hub.

**Comment by strugee** [comment]
http://pump.io/blog/2018/05/pump.io-5.1.1-docker-images-and-node-4
