### ISSUE TITLE
Follow remote incompatible between 5 and 3.x

### ISSUE THREAD

**Issue by vxcamiloxv** [pump-io/pump.io#1443]
I was test this issue with `identi.ca` and `http://awkwardly.social` and get same error `Unable to connect`, the two instances has pump.io 3.x, My instance is from `master` (5.x), instances with version 4 and 5 works fine

![pump error](https://ibin.co/w800/3ZVVIJf3HBG7.png)

**Comment by strugee** [comment]
You're just clicking "login with remote account" right?

**Comment by vxcamiloxv** [comment]
Yes.

**STR's:**
1. Navigate to any remote user (identi.ca)
2. Click on *Follow*
3. Click on *Account on another server?*
4. Insert my *Webfinger ID* 
5. Redirect to my domain */oauth/authorize?oauth_token=Ghsu..*
6. Click on *Authorize*
7. Redirect to *https://identi.ca/main/authorized/..*
8. Unable to connect

**Actual Results:**
Show `ERR_EMPTY_RESPONSE` or Unable to connect

**Expected Results:**
Redirect to user profile and login as a remote user

**Comment by strugee** [comment]
Okay. This was actually fixed in be6c1e46ebee1dde7f203017c0decb88c06b2a6f, which went out in 5.0 and was backported to the stable at the time, 4.1, in 4.1.1.

Thanks for reporting though :)
