### ISSUE TITLE
express-session memory leak

### ISSUE THREAD

**Issue by roccomuso** [pump-io/pump.io#1472]
The default "memory" storage for sessions suffer a well known memory leak. As pointed out on the `express-session` documentation. The usage is discouraged in production.

Consider switching to a leak-proof in-memory store: [memorystore](https://github.com/roccomuso/memorystore)

**Comment by vxcamiloxv** [comment]
Pump.io save session according to db driver, `redis`, `mongodb`, etc, the documentation say: "the disk or even memory drivers can work for testing", then you should not use `memory` for production.

**Comment by strugee** [comment]
As @vxcamiloxv said, pump.io does not use express-session's `MemoryStore`.

Looking at your GitHub profile it looks like you're copying and pasting this issue across many projects. If they were actually impacted that'd be one thing, but in this case (and I can only assume others) you've spammed this issue tracker to advertise your project for an issue that doesn't even apply to this repository. That's pretty rude - please don't do that again.
