### ISSUE TITLE
e14n.com is down

### ISSUE THREAD

**Issue by Serkan-devel** [pump-io/pump.io#1488]
Has anyone notified Evan about it?

**Comment by vxcamiloxv** [comment]
@Serkan-devel  I think is not related with Pump.io, please contact the instance maintainer @evanp

**Comment by strugee** [comment]
Typically we notify Evan when his nodes go down but I think admin@e14n.com doesn't work now either. @larjona has anyone contacted Evan? Do we know what email works?

**Comment by vxcamiloxv** [comment]
Probably: https://evancoin.com/contact/

**Comment by larjona** [comment]
El 4 de noviembre de 2017 22:54:59 CET, Camilo QS <notifications@github.com> escribió:
>Probably: https://evancoin.com/contact/

Hi, I've jist sent an email to his contact email (which was working in September at least). 
Let's close this bug, I'll keep people informed via IRC (or calling for community meeting).

Cheers
Laura Arjona Reina
https://wiki.debian.org/LauraArjona
