### ISSUE TITLE
Running pump.io on a raspberry pi docker image(arm 32-bit)

### ISSUE THREAD

**Issue by Serkan-devel** [pump-io/pump.io#1495]
I'm trying to run pump.io (as the title explains it) but there are issues with running mongodb https://groups.google.com/forum/#!msg/mongodb-user/c7O-BdFe-fE/kIIW1O-KBQAJ

Does this project actually work on Raspberry pi's like as explained <a href="https://en.wikipedia.org/wiki/Pump.io#Technology">here</a>?

Are there any build instructions for it?

**Comment by vxcamiloxv** [comment]
I ran pump.io in Raspberry pi without docker and with redis and worked fine.

**Comment by Serkan-devel** [comment]
@vxcamiloxv did it need mongo?

**Comment by vxcamiloxv** [comment]
@Serkan-devel Not, because, I used redis `databank-redis`

**Comment by Serkan-devel** [comment]
How does one configure pump.io to use redis instead of mongo?

**Comment by vxcamiloxv** [comment]
@Serkan-devel 
1) Install redis in you raspberry Pi depending of you distribution.

2) In pump.io directory install a databank redis

```bash
  npm install databank-redis
```

3) In your config add driver config something like that.

```json
  "driver": "redis",
  "params": {
    "port": 6379,
    "database": "1"
  },..
```

**Comment by strugee** [comment]
@Serkan-devel did you figure it out? If so I'll close this issue :)

Otherwise we'd be happy to help.

**Comment by Serkan-devel** [comment]
I'm working on it

**Comment by strugee** [comment]
I'm closing this since it's been inactive for a while but if you run into problems again ping me so I can reopen.

**Comment by Serkan-devel** [comment]
@strugee I want to make a docker build of it

**Comment by Serkan-devel** [comment]
In armhf
