### ISSUE TITLE
FEATURE REQUEST: add version # to web UI

### ISSUE THREAD

**Issue by douglasawh** [pump-io/pump.io#1501]
GNU Social (or at least the main instance where I have an account, but I think I've seen it elsewhere) says "It runs on GNU social, version 1.2.0-beta4, available under the GNU Affero General Public License." My pump admin doesn't think that information is exposed other than in http headers. It would be useful for bug reports.

**Comment by jankusanagi** [comment]
https://github.com/pump-io/pump.io/issues/1436

**Comment by strugee** [comment]
Closing as a dupe of #1436. Thanks @douglasawh!

**Comment by douglasawh** [comment]
It's not which is why I reopened. 1436 asks for footer. That's not what I'm asking. Just put it in settings or something.

**Comment by strugee** [comment]
Noted. I'm changing #1436 to be more generally about putting the version somewhere in the web UI, to keep the issue tracker clean.
