### ISSUE TITLE
Thumbs down icon is still black when you've just clicked "like"

### ISSUE THREAD

**Issue by strugee** [pump-io/pump.io#1520]
That is, the custom JavaScript logic produces black icons but the templates (which get used when the page is refreshed) use the white icon. Yet another issue that would be solved by #1240...

**Comment by vxcamiloxv** [comment]
So, the Thumbs down should be blue when is clicked?

**Comment by strugee** [comment]
No, it should be white to match the rest of the icons

**Comment by strugee** [comment]
Just try this out yourself and you'll see - to be precise it's not the white icon, it's the icon without fill

**Comment by vxcamiloxv** [comment]
I confirm this issue, I could reproduce in datamost.com, in my server couldn't reproduce that issue because I implemented some logic improves that fixed this: https://github.com/vxcamiloxv/pump.io/tree/fix-update-major-activity
