### ISSUE TITLE
Don't send emails about activities you've performed yourself

### ISSUE THREAD

**Issue by strugee** [pump-io/pump.io#1537]
E.g. "AJ posted a reply" or whatever. I don't need to know about what I've already done myself.

Triaging as Near Future since this is a papercut that's probably a pretty small change to fix.

**Comment by larjona** [comment]
I've seen in other places that this was an option that the user could check in their profile.
Sometimes it's useful to receive own activiy (e.g. shared/institutional account with an email alis that goes to every person using that account).

Thanks!

El 8 de marzo de 2018 6:15:53 CET, AJ Jordan <notifications@github.com> escribió:
>E.g. "AJ posted a reply" or whatever. I don't need to know about what
>I've already done myself.
>
>Triaging as Near Future since this is a papercut that's probably a
>pretty small change to fix.

-- 
Laura Arjona Reina
https://wiki.debian.org/LauraArjona
Sent with K-9 mail

**Comment by strugee** [comment]
Duplicate of #738.
