### ISSUE TITLE
Test user and token in configuration

### ISSUE THREAD

**Issue by evanp** [pump-io/pump.io#1558]
We spend a lot of cycles in the test code registering new users and authorizing new tokens for them.

We should allow specifying one or more test users, applications and tokens at server startup as part of the configuration.

The server can ensure that the users, apps and tokens exist in the db.

No default should be provided. We don't need a baked-in backdoor.

This can all be guarded with checks for node environment == development.

**Comment by strugee** [comment]
There's already `clients` for applications; see https://pumpio.readthedocs.io/en/latest/configuration/reference.html. Makes sense to do this for users and tokens too.
