### ISSUE TITLE
Test ActivityPub endpoints with OAuth 2.0 bearer tokens

### ISSUE THREAD

**Issue by evanp** [pump-io/pump.io#1560]
We're currently using the OAuth 1.0 tokens to test these endpoints. We need to test with bearer tokens, both as a header and as a query parameter.

**Comment by Serkan-devel** [comment]
What about OAuth 2?

**Comment by evanp** [comment]
Yeah, this issue is about OAuth 2.0.

I changed the activitypub-* tests to use OAuth 2.0 instead of 1.0, so I'm closing this.
