### ISSUE TITLE
Unable to authorize from remote server

### ISSUE THREAD

**Issue by Serkan-devel** [pump-io/pump.io#1565]
I can't authorize identi.ca from my datamost.com-account when logging in. On the Authorization page, when clicking on [Authorize], a connection can't be established. Is it due to registrations being disabled?

**Comment by jankusanagi** [comment]
AFAIK, that's a problem with identi.ca still using Pump.io v3.x.

For now, depending on what you need to do, using [a non-web client](https://pumpio.readthedocs.io/en/latest/clients.html#desktop) might help.

**Comment by strugee** [comment]
Yep. Unfortunately there's nothing we can do. We need @evanp to upgrade identi.ca.

**Comment by evanp** [comment]
Wait, what? Since when did the authorization protocol change?

**Comment by strugee** [comment]
It didn't, but for a while there was a crasher bug in the auth code.

**Comment by strugee** [comment]
https://github.com/pump-io/pump.io/blob/master/CHANGELOG.md#411---2017-07-14

**Comment by Serkan-devel** [comment]
@evanp has identi.ca already been updated?

**Comment by strugee** [comment]
Yes
