### ISSUE TITLE
Uploaded files sent to Followers aren't visible to the author

### ISSUE THREAD

**Issue by evanp** [pump-io/pump.io#1570]
I get a 403 error when I try to view an image I posted on identi.ca to Followers. If I post it to Public, it's fine.

**Comment by strugee** [comment]
See #1438

**Comment by evanp** [comment]
So this is fixed in master? If so, how about publishing 5.1.1?

**Comment by strugee** [comment]
5.1.1 is out; sorry it took so long! http://pump.io/blog/2018/05/pump.io-5.1.1-docker-images-and-node-4
