### ISSUE TITLE
jade -> pug

### ISSUE THREAD

**Issue by evanp** [pump-io/pump.io#1575]
I get the deprecation notice every time I `npm install`. Jade is now pug; let's use pug.

**Comment by evanp** [comment]
Is it semver-major? Why? I thought it was the same syntax, different name.

**Comment by Serkan-devel** [comment]
What about lit-html?

**Comment by strugee** [comment]
It's almost entirely the same syntax but we consider merging non-trivial template patches to be semver-major

**Comment by strugee** [comment]
@Serkan-devel when I switched us over from utml to Jade it took ~17 hours of mindless translation. I am not about to do that again.

**Comment by Serkan-devel** [comment]
oh

**Comment by evanp** [comment]
@strugee ok. I don't think the template files have to change at all, though.

**Comment by strugee** [comment]
@evanp I was thinking the file renames would be problematic but now that I think about it, I don't think so. git should handle that.

**Comment by evanp** [comment]
@strugee I guess maybe if people have custom templates, that's a problem? ISTR that we were treating changes there as semver-relevant.

I think we could do it like, look for .jade first, and if it's not there, look for .pug?

**Comment by strugee** [comment]
@evanp LGTM. FWIW, see https://github.com/pump-io/pump.io/blob/master/CHANGELOG.md#pumpio-changelog where I have documented what we consider semver-major. I guess we should add custom template files to the list?
