### ISSUE TITLE
PUMP_LOCATION = /opt/pumpio in Dockerfile

### ISSUE THREAD

**Issue by evanp** [pump-io/pump.io#1592]
Not a big deal, but I think packages like pump.io are supposed to go into /opt/ directories rather than /usr/local/lib.

People put stuff in wack places in Dockerfiles. That said, `/usr/local/lib` is usually used just like `/usr/lib`, except for locally-installed software. `/opt/` is usually used for packages that fit different kinds of files in a single tree.

https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

**Comment by strugee** [comment]
I have this fixed locally. Should we still install a symlink to /use/local/bin, I wonder? Guess I'm bikeshedding a bit
