### ISSUE TITLE
Listen on port 80 by default in Dockerfile

### ISSUE THREAD

**Issue by evanp** [pump-io/pump.io#1594]
The Docker image should listen on ports 80 and 443, instead of on the rando port we use for debug testing.

**Comment by Serkan-devel** [comment]
Maybe use something like port 8080 or another unspecified port because this needs more system privileges to run. And I see web-projects like this always use 4-digit ports like port 5000

**Comment by evanp** [comment]
No, Docker projects usually listen on 80 and 443
