### ISSUE TITLE
first news blog link at https://pump.io is 404

### ISSUE THREAD

**Issue by ian-kelling** [pump-io/pump.io#1635]
pump.io 5.1.1, Docker images, and sunsetting Node 4 support
to http://pump.io/blog/2018/05/pump.io-5.1.1-available-and-docker-images

**Comment by Serkan-devel** [comment]
![screenshot_20180515-201425](https://user-images.githubusercontent.com/16866642/40075510-be7cd1a2-587c-11e8-8778-91ac8a59a057.png)

**Comment by strugee** [comment]
Wow, nice catch. That's embarrassing.

I'll be fixing this shortly.
