### ISSUE TITLE
Introduce a control socket and a `pumpctl` command

### ISSUE THREAD

**Issue by strugee** [pump-io/pump.io#1643]
Right now you trigger zero-downtime restarts with `SIGUSR2`. This is not great for two reasons:

1. If you have other Node processes running on the system, you can't blindly do `killall -USR2 node` because Node's default behavior on receiving SIGUSR2 is to crash, so you'll kill your other processes
2. It doesn't leave any room open for other behavior - for example, for #1270 we might want to have a way to ask the daemon to reopen its logs

In order to solve both of these problems I propose that we:

1. Deprecate SIGUSR2 as a way of controlling zero-downtime restarts
2. Introduce a Unix domain control socket that will be placed in `/run` (by default)
3. Add a `pumpctl` command that will talk to the socket and let you request actions like zero-downtime restarts, log reopening, etc.

We'd make sure the socket was owned by root so not just anyone could talk to it. I don't want to deal with having authentication because that means the control socket handling would have to have a notion of sessions and be stateful and that sounds terrible.

@evanp, can you tell me if this is a horrible idea? I think other programs do this; the one that comes to mind right now is Tor but I'm not sure how many others there are.

**Comment by BigAlInTheHouse** [comment]
Through which Linux distro would you suggest or os?

**Comment by Serkan-devel** [comment]
Any Linux distro that can run node?

**Comment by strugee** [comment]
Evan confirms on IRC that this is not a terrible idea.
