### ISSUE TITLE
No proper error message display

### ISSUE THREAD

**Issue by jmtiong** [pump-io/pump.io#1676]
Greetings,

I have tried to use the https://datamost.com/main/register to register for an account and after successfully logged in without any verification to the email address, there are some error messages that I do not understand. Clicking on any of the links will display "undefined" error message.

![image](https://user-images.githubusercontent.com/16659123/43504390-d9d62bf0-9595-11e8-8968-1a924abe681e.png)

When I view the network log in the developer console, it did return the error message 

![image](https://user-images.githubusercontent.com/16659123/43504418-f4af3b42-9595-11e8-99b2-67c7481d2f01.png)

### Expected behavior

I feel that it should return the exact message of why I am unable to use the API rather than just "undefined" message.

If you want to replicate the bug, I did created a test script using Uilicious.

![ezgif com-optimize 4](https://user-images.githubusercontent.com/16659123/43504953-d81451c8-9597-11e8-8545-9e7b8f5236ea.gif)

Here's the script that I used to test it
```javascript
// Register for an account
I.goTo("https://datamost.com/main/register");
I.fill("Nickname", "testing_1");
I.fill("#email", "testing1@random.com");
I.fill("Password", "abc123456");
I.fill("Repeat", "abc123456");
I.click("Register");

// Login procedure
I.goTo("https://datamost.com/main/login");
I.fill("Nickname","testing_1");
I.fill("Password","abc123456");
I.click("Login");

// Assert that I am logged in
I.see("Picture");
I.see("Note");
I.goTo("https://datamost.com/");
I.see("testing_1 joined datamost.com");

// No proper error display
I.see("Coworkers");
I.click("Coworkers");
I.see("Can't use the API until you confirm your email address.");
```

**Comment by strugee** [comment]
Hi @jmtiong, thanks for reporting this issue!

This is definitely a problem. I think that #1122 probably encompasses this issue, would you agree? If so I'd like to close as a duplicate of #1122.

**Comment by vxcamiloxv** [comment]
Already exist a PR to fix this issue: https://github.com/pump-io/pump.io/pull/1352

**Comment by jmtiong** [comment]
@strugee @vxcamiloxv agree and thanks a lot! I'll close this issue :)
