### ISSUE TITLE
Cannot follow account on pump.io server using Mastodon account?

### ISSUE THREAD

**Issue by c933103** [pump-io/pump.io#1684]
I get an 500 error when I tried to follow @wikipedia@identi.ca or @andstatus@identi.ca using my Mastodon account on pawoo.net

**Comment by strugee** [comment]
This is because pump.io does not do ActivityPub (yet). I'm on mobile so I don't want to deal with stuf searching but you should probably be able to find the issues where we're tracking this stuff pretty easily.

**Comment by strugee** [comment]
Couldn't help myself. Duplicate of #1241

**Comment by c933103** [comment]
Thanks.

**Comment by strugee** [comment]
No problem, and thanks for checking out pump.io!
