### ISSUE TITLE
Suspicious: https://e14n.com/ is redirecting to https://activex.windowss10.com/ 

### ISSUE THREAD

**Issue by eliasbaixas** [pump-io/pump.io#1689]
the domain e14n.com may have been bought by some outsider,
and now redirects to https://activex.windowss10.com/

which is quite a bit suspicious.

it should get removed at least from the home page http://pump.io/

**Comment by strugee** [comment]
Thanks for the report. @evanp is going to try to get e14n.com back.

**Comment by strugee** [comment]
Seems like he already did? Evan, feel free to close.
