### ISSUE TITLE
OFirehose is broken

### ISSUE THREAD

**Issue by prologic** [pump-io/pump.io#1698]
According to the [docs](https://pumpio.readthedocs.io/en/latest/clients.html)

> [OFirehose](https://ofirehose.com/) - The pump network firehose.

This is broken and returns `ERR_CONNECTION_REFUSED`

This is a KP? Who runs this service? It is referenced in the default configuration. Does anyone actively maintain it?

**Comment by vxcamiloxv** [comment]
That service is provided by @evanp, but anyone can run your own instance https://github.com/e14n/ofirehose

**Comment by prologic** [comment]
> That service is provided by @evanp, but anyone can run your own instance https://github.com/e14n/ofirehose

I see... Whic is apparently offline and not well maintained or @evanp would have ensured it was properly maintained?

In any case... Excuse my ignorance, but how does spinning up your own OFirehose instance help here when the default configuration is @evanp 's URI? -- More to the point what is the point of a "Global Timeline" if you can configure your own set of N instances to publish to your own OFirehost? Am I even making sense? :)

**Comment by vxcamiloxv** [comment]
@prologic you can set up your own firehose instance and offer that to the public that way others can use it, but I think is the service not back in a few months the best option is changed the default suggested config, I'll close the issue if you have more question about the status or the ofirehose and the service open an issue in the another repo, thanks

**Comment by prologic** [comment]
I see... I'd be happy to host one in place of the existing broken/offline one if that helps? Assuming I can get the rest of my instance up and running without running into bugs  :/
