### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by benswen** [pump-io/pump.io#1709]
I'm relatively new to GitHub, so forgive me if this is not the correct place to ask. However, I tried to install this using the recommended steps in the documentation and got several deprecated warnings as well as an "Unsupported engine...wanted node >=4 <=8" warnings. So...is this project dead?

**Comment by strugee** [comment]
See https://github.com/pump-io/pump.io/issues/1697#issuecomment-497540253, and more recently https://github.com/w3c/activitypub/issues/347#issuecomment-606971945.

Closing on the assumption that those answer your questions, but if not let me know and I can reopen :)
