### ISSUE TITLE
Display / encoding issues with site name in web client

### ISSUE THREAD

**Issue by warpr** [pump-io/pump.io#343]
![pump-io-encoding-issues](https://f.cloud.github.com/assets/85700/62228/6e0bb2aa-5ced-11e2-8cad-51e5e1399fa6.png)

**Comment by strugee** [comment]
Hey @warpr, I don't suppose you have the config file you used still lying around? Otherwise I'd like to close this. Thanks!

**Comment by warpr** [comment]
@strugee correct, I don't have the config file anymore.

**Comment by strugee** [comment]
@warpr okay, thanks. I'll try and reproduce this and close if I can't. Sorry we didn't get to it in time :-)

**Comment by strugee** [comment]
Okay, I'm assuming this was just the slashes getting incorrectly HTML-escaped, so I ran `node bin/pump --site 'my//test//pump'` and couldn't reproduce this. Closing as fixed, probably by the new XSS sanitizer that landed a year or two ago in #1184.
