### ISSUE TITLE
Single‐user mode

### ISSUE THREAD

**Issue by johndrinkwater** [pump-io/pump.io#422]
Like StatusNet’s http://status.net/wiki/Single-user_mode, be able to configure a single account for the server.
#388 is somewhat related, as the user ID could be stripped.

**Comment by larjona** [comment]
I think registering an account and then closing registrations is the way to go.
If nobody proposes a plan for this feature in the following months, I think we can close the issue, and then reopen it when somebody offers some code to implement it.

**Comment by strugee** [comment]
Closing since I agree @evanp's position that you can easily accomplish this already and doing a "proper" version would introduce lots of complexity.

If anyone has a compelling reason that won't work, comment here and we can revisit this discussion.
