### ISSUE TITLE
Silly default server names

### ISSUE THREAD

**Issue by sudoman** [pump-io/pump.io#480]
i created an account already, but what if i want to move to pump.io later, if and when there is a migration feature from other platforms? am i able to delete an account from a server in the meantime?

also, i the name of the random server i just joined isn't the coolest... (poor me... ;p ) i think that could be a issue for people in the future. they might not like the idea of having friends contacting their official handle, if it's very_serious_guy_or_gal@pumpity.net or your_loving_mother@pumpyourself.com.

**Comment by strugee** [comment]
I don't think there's anything to do here, right? Objections to closing?
