### ISSUE TITLE
Unexplicable autarky instance: can't achieve to follow a remote user on a remote pump server

### ISSUE THREAD

**Issue by blankoworld** [pump-io/pump.io#570]
Thanks to some tutorial I create a new pump.io serveur. (Cf. http://whird.jpope.org/2013/03/27/pump/ ).

Pump: trunk version (a58da13c27b4a841186b7d4582a19a66abd34731)
Pump server OS: Xubuntu 11.04
Redis DB
Proxy: Nginx v1.3.16 on Debian Squeeze
Browser: Firefox 18.0.2

All is ok to add users, follow them, etc.

But what's curious is that following people on remote server is a kind of bumpy road!
- Using "another server" login on remote server works 1/2. Sometimes it work perfectly, sometimes it take a long time to show an "hang up".
- Then, when logged in on remote server, I try to follow someone. I click on "follow". Nothing happen (probably due to Firefox?). Then I relaunch webpage, I click on follow => success \o/. But what's strange : I do not appear in it's followers ! In fact I cannot receive anything from this remote user because I'm not it's follower. And my pump server said that i'm following it!

So as a barbaric user, I do: "Stop following" button. (this does not work the first time, I reclick). Then I attempt to follow it again. But as explained, nothing happens.

Which kind of logs/explanation/information should I give you? Is that a well-known problem of misconfiguration or something else?

**Comment by strugee** [comment]
Hey @blankoworld. Do you still have a pump instance set up? Can you still see this error?

**Comment by blankoworld** [comment]
Hello here :).

Sorry, I didn't have any pump instance yet. So I can't reproduce the error. As it's an old ticket, you can close it.

**Comment by strugee** [comment]
Cool. Thanks for the quick response!
