### ISSUE TITLE
More informative error message on Bad request

### ISSUE THREAD

**Issue by shtrom** [pump-io/pump.io#623]
Currently, when the server returns a Bad request to an XMLHttpRequest, the web interface only displays a box saying “Bad request”.

The error reply is however slightly more verbose, containing a description of the error (e.g, “Invalid signature” in #455).

Would it be possible to capture this text from the reply, and display it in the error box alongside the Bad request message?

**Comment by vxcamiloxv** [comment]
I think this is already handled on the client side with: https://github.com/pump-io/pump.io/pull/1352, please open again otherwise
