### ISSUE TITLE
More granularity in logging

### ISSUE THREAD

**Issue by msjoberg** [pump-io/pump.io#634]
Currently the pump.io log is either on of off by setting the "nologger" option in the config file. With logging on it is however very verbose, for example every communication with the web browser seems to cause a huge chunk of JSON. My instance which only has a single user and not much stuff happening produces a log file of about 25 MB every day.

It would be nice to be able to have different levels of verbosity at least, or better yet the ability to choose what types of stuff you want to have logged.

**Comment by strugee** [comment]
This has existed for a long time but was undocumented. See 22571897b637f3e9be624a7d7c55bb3d68dda0d8 and #1390.

Closing as this seems to be resolved :thumbsup:
