### ISSUE TITLE
First-time clicking on image (picture) does not open it centered nor resized

### ISSUE THREAD

**Issue by larjona** [pump-io/pump.io#639]
When I click for first time in a picture posted by somebody, a tiny square opens in the center of the picture, and then after 1 second or so, the picture itselfs is opened but not centered: from center to right down corner (and not resized to fit the screen). See attached file.
After clicking in other place in the screen, the picture is closed. Then, if I click again to see the picture, it is open centered in my screen and resized (the correct way).
Tested in Iceweasel 21 and Chromium in Debian stable and the issue occurs.
Tested in Firefox 21 in Windows XP and Win7 and the issue occurs.
Tested in IE 10 in Windows 7 and the issue occurs.
Tested in Android 2.3.4 and default browser and Zirco browser and the issue does not occur (the image displays correctly from the first time). The problem with these browsers is that clicking in other place to close the image does not work.
![2qa_qg](https://f.cloud.github.com/assets/1420240/613426/0f94c1bc-ce03-11e2-96f9-18b225aba9df.png)

**Comment by mrvdb** [comment]
Came here as I have this same issue.  Wow, open since 2013!

**Comment by strugee** [comment]
@mrvdb I would be happy to review a Pull Request fixing this :-)

**Comment by mrvdb** [comment]
@strugee I was just surprised, as the issue doesn't **_sound_** very difficult, but perhaps I'm overlooking something. I'll try to free up a slot and have a look.

**Comment by strugee** [comment]
@mrvdb I don't know, my CSS isn't very good :P

Mostly we've just had many other priorities. There are lots of small issues like this that haven't been fixed just because of time constraints.

**Comment by vxcamiloxv** [comment]
Already exist a PR to fix this since Oct 2017 https://github.com/pump-io/pump.io/pull/1465

**Comment by mrvdb** [comment]
Awesome! Will test it this weekend.

**Comment by vxcamiloxv** [comment]
@mrvdb  for large images load a bit slow, I think this requires a spinner/loader or show a medium size, currently pump.io only have two sizes (original and small), I think should be another ticket.

**Comment by vxcamiloxv** [comment]
@mrvdb  I added a spinner to indicate the image is loading https://github.com/pump-io/pump.io/pull/1465/commits/f406e04390599832d62a2d331f42f6dcb91ec268

**Comment by mrvdb** [comment]
@vxcamiloxv perfect!
