### ISSUE TITLE
Use Meteor for web UI

### ISSUE THREAD

**Issue by mitar** [pump-io/pump.io#660]
I believe [http://meteor.com/ Meteor] would be a great node.js framework to build web UI upon. I see that real-time updates do not propagate perfectly currently (like if I have to windows open with same note and I comment in one, comment does not appear in the other) and Meteor makes such things really easy to implement.

**Comment by strugee** [comment]
We're not going to do this. AFAIK using Meteor would require rewriting the entire backend too and that's a non-starter. See also #1240
