### ISSUE TITLE
Crypto support

### ISSUE THREAD

**Issue by shtrom** [pump-io/pump.io#663]
It would be neat to be able to add cryptographic signatures to notices and comments. Some though should be put into some algorithm flexibility not to tie Pump.io down too much to one crypto system (PGP, SSL, ...).

Maybe even encrypt them or have an OTR activity stream (these might however not be really relevant in a broadcast medium).

**Comment by strugee** [comment]
Closing as there's nothing for us to do in core. Anyone who wants this can write/patch a client to do so
