### ISSUE TITLE
Liking a note hides new comments

### ISSUE THREAD

**Issue by mvdan** [pump-io/pump.io#685]
If you add a comment to a note, wait a few seconds and then like the original note, your comment will disappear. It will re-appear if you reload the page.

Just as well, it seems that liking a note will show "You like this" on the note as well as all the comments below it, even though you're not liking these. So one must reload the page if he wants to like the note and one of the comments to it.

**Comment by mvdan** [comment]
Ignored (abandoned?), so removing from my issue backlog.

**Comment by strugee** [comment]
Look around in this issue tracker. It's active, but we have 500+ open issues. This one just hasn't been a priority.
