### ISSUE TITLE
Tool to check pump

### ISSUE THREAD

**Issue by eoyarzabal** [pump-io/pump.io#688]
I think it like a tool to check if my own pump is working ok with the others or not.
Like does pingdom.com to the sites but it can check with the others to shutdown the connection and don't wait for it if the "pong" was not received.

**Comment by strugee** [comment]
I'm not sure I understand what's desired here. @eoyarzabal, can you spell out in detail what you want?

**Comment by eoyarzabal** [comment]
Sorry, was an old thinking. I'm not a pump user anymore.
