### ISSUE TITLE
email notification have a weird <p> tag

### ISSUE THREAD

**Issue by anarcat** [pump-io/pump.io#739]
I got the following notification:

```
The Anarcat,

You were addressed in an activity.

    https://identi.ca/anarcat/activity/gxAOPS6cQ-Oq3I1gvq5XOQ

<p>If you think you received this email in error, you can safely ignore it.</p>
```

This is the plain text version of the HTML, but I am guessing it's manually generated, because the HTML version is:

```
<p>The Anarcat,</p>

<p><a href='https://identi.ca/anarcat'>The Anarcat</a> favorited <a href='https://identi.ca/evan/comment/sJklnQngQGuRQjQW1n5UwQ'>a comment</a> in reply to a note</p>


<blockquote><a href="https:&#x2F;&#x2F;identi.ca&#x2F;anarcat&#x2F;activity&#x2F;gxAOPS6cQ-Oq3I1gvq5XOQ">more information</a></blockquote>


<p>If you think you received this email in error, you can safely ignore it.</p>
```

This is nitpicking, really, because it doesn't affect functionality much, but it would be nice to have that output be prettier.

**Comment by brainwane** [comment]
I am guessing this is the problem discussed by @jankusanagi in https://identi.ca/jankusanagi/comment/5hjE2MhoRbWJNxhwBLTdIg & in https://identi.ca/brainwane/note/8sXpyp19R6uaeWd8zfjYXg that makes #497 even more of a problem for my interaction with the service.

**Comment by strugee** [comment]
This problem seems to be fixed. If you still experience this problem in a reasonably modern version of pump.io, please comment here and I'll reopen. Cheers!
