### ISSUE TITLE
ActivityStreams 2.0 support

### ISSUE THREAD

**Issue by liamzebedee** [pump-io/pump.io#851]
Recently the [draft for ActivityStreams 2.0](http://tools.ietf.org/html/draft-snell-activitystreams-04) was published, which 

> ...builds upon that initial foundation by incorporating lessons learned through extensive implementation, community feedback and related work being performed in other standards development communities.

In the near future it would most likely be beneficial to implement this newer spec, seeing as Pump is the image of a successful AS project right now.

**Comment by strugee** [comment]
This will go into the release after next, along with ActivityPub (probably).

**Comment by evanp** [comment]
What's the difference between #1483 and #851?

**Comment by akuckartz** [comment]
#851 is an issue and #1483 is a pull request intended to resolve that issue.

**Comment by Serkan-devel** [comment]
Will Activitystreams and Activitypub get implement at the same time?

**Comment by strugee** [comment]
Well, AS2 landed on `master` a week and a half ago. I believe Evan is still hacking away on the AP implementation. It's likely that it'll ship at the same time but we're not sure.
