### ISSUE TITLE
The word 'write' followed by a space and a single quote ( ') loses the space

### ISSUE THREAD

**Issue by jacobwb** [pump-io/pump.io#852]
When posting a note such as the following:

"I need to write 'this person' a long letter."

It becomes:

"I need to write'this person' a long letter."

A simple bug, however, it's possible there are more words that get this treatment.

Affected version: Whichever Identi.ca runs.

**Comment by strugee** [comment]
@larjona can you still reproduce this?

**Comment by larjona** [comment]
No, I can't. Closing the issue, thanks for caring.

**Comment by strugee** [comment]
Thanks @larjona!
