### ISSUE TITLE
Upgrade to Express 4.x

### ISSUE THREAD

**Issue by matzegebbe** [pump-io/pump.io#877]
i am working on the implementation of a newer express version in pump.io.
i miss a few functions and this will solve my problems (hope so).

is there a reason against this?

**Comment by strugee** [comment]
FWIW this work is going on in the `express-3.x` branch. The plan is to do a release with Express 3.x so we get some feedback on regressions, etc., then move to Express 4.x. (The latter change will probably be much easier.)

**Comment by strugee** [comment]
Removing webui label as this powers the API as well as the web UI.

**Comment by strugee** [comment]
This just landed in #1208; pump.io 4.0 will be powered by Express 4.x.
