### ISSUE TITLE
Server up and running but http GET got no response

### ISSUE THREAD

**Issue by yhzhao** [pump-io/pump.io#993]
Hi,
Sorry for the novice-level question.

I installed the latest build on an Amazon ec2 and starts the server, the configuration seems to be ok. I use mongodb. There is no complaints in std err/io or log, and server is listening on port 8000. But when I use a web browser pointing to http://ec2-public-ip:8000, nothing happens. https does not make any difference.

I must have missed some basic steps. Can some expert help me out? Is there a way to bump up the debugging level? Do I need to create a customized .js from the template? (I am clueless, simply brain-storming now.)

Thanks in advance.

Y.Z.

**Comment by strugee** [comment]
@yhzhao do you still need help? If not I'd like to close this
